### ISSUE TITLE
XPATH: Suggestion for additional syntax: @Attribute(number)

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/packages-sgml#10]
Consider an XML fragment like:

    <td attr="5">2</td>

With `library(xpath)`, we can easily extract the number `2`:

<pre>
?- AST = [element(td, [attr='5'], ['2'])],
   xpath(AST, //td(<b>number</b>), X).
</pre>

We can also easily access the value of the attribute `attr`:

<pre>
?- AST = [element(td, [attr='5'], ['2'])],
   xpath(AST, //td(@attr), A).
A = '5' .
</pre>

Now suppose that we want to extract the value of the attribute `attr` like above, and at the same time convert it to a number.

To do this, please consider adding the syntax `@Attribute(number)` or a similar feature, so that one can write:

<pre>
?- AST = [element(td, [attr='5'], ['2'])],
   xpath(AST, //td(@attr(<b>number</b>)), A).
<b>A = 5 </b>.
</pre>

This would make extracting numeric attributes easier, and it is a natural extension of the already available syntax.

**Comment by JanWielemaker** [comment]
Added with da0b1b57bc116b7365817100cfdcb9cd06f5e227
