### ISSUE TITLE
Year 1 BCE is unsupported and years _N_ BCE for _N_ > 1 are off by one

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-sgml#13]
### Year 1 BCE is unsupported

```prolog
?- rdf_equal(xsd:gYear, D), xsd_time_string(X, D, '0000').
ERROR: sgml:xsd_time_string/3: Domain error: `year' expected, found `0'
```

Expected: `X = -1`.

### Years _N_ BCE for _N_ > 1 are off by one

```prolog
?- rdf_equal(xsd:gYear, D), xsd_time_string(X, D, '-0001').
D = 'http://www.w3.org/2001/XMLSchema#gYear',
X = -1.
```

Expected: `X = -2`.

### Reference

The relevant part form the XSD 1.1 specification:

> The lexical representation '0000' for years is recognized and maps to the year 1 BCE; '-0001' maps to 2 BCE, etc. This is a change from version 1.0 of this specification, in order to align with established practice (the so-called "astronomical year numbering") and [ISO 8601].

**Comment by JanWielemaker** [comment]
Should be fixed.
