### ISSUE TITLE
Why is it 1.5NaN?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-sgml#20]
Is the following correct?  Why is it `1.5`?

```prolog
?- [library(sgml)].
?- xsd_number_string(N, 'NaN').
N = 1.5NaN
```

**Comment by JanWielemaker** [comment]
It is correct.  I copied the ECLiPSe way to deal with NaN.   Note that in the IEEE float representation there is not just a single NaN.   It is a reserved value of the mantises that defines a float to be NaN; the rest may have any value.  For Prolog purposes we need something that is not reserved by the Prolog syntax and for equality preservation a way to represent the different NaN values.   A float followed by what would normally be a variable suits this purpose.

**Comment by wouterbeek** [comment]
But why is it `1.5NaN`?  E.g., `xsd_number_string(1.0NaN, X)` gives an error.

**Comment by JanWielemaker** [comment]
See http://www.swi-prolog.org/pldoc/man?section=floatsyntax.  The docs aren't very clear that 1.0 itself is not allowed.   The current support for NaN and Inf do not allow much more than round tripping them as these numbers are traditionally not part of Prolog.

**Comment by wouterbeek** [comment]
Thanks!
